version: '3.9'

services:
  admindbs:
    image: mariadb:10.11
    container_name: admin_mariadb_login
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - admindbs
    environment:
      ADMINER_DEFAULT_SERVER: admindbs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build: .
    container_name: admin_dashboard_login_app
    restart: always
    env_file:
      - .env
    depends_on:
      - admindbs
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  thaid:
    build:
      context: ./thaid/
    container_name: nsf-linkage-thaid
    environment:
      - TZ=Asia/Bangkok
      - PORTS=3000
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK=${CALLBACK}
      - API_KEY=${API_KEY}
      - API_DB_URL=${API_DB_URL}
      - XUSERNAME=${XUSERNAME}
      - XPASSWORD=${XPASSWORD}
      - STATE=a21bce34
      - scope=pid name name_en birthdate address given_name middle_name family_name given_name_en middle_name_en family_name_en gender smartcard_code title title_en date_of_issuance date_of_expiry
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
    ports:
      - 3005:3000
volumes:
  db_data:

networks:
  default:
    name: webnet
    driver: bridge
    external: true